<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\State;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districts = [
            'Andhra Pradesh' => [
                'Anantapur',
                'Chittoor',
                'East Godavari',
                'Guntur',
                'Kadapa',
                'Krishna',
                'Kurnool',
                'Nellore',
                'Prakasam',
                'Srikakulam',
                'Visakhapatnam',
                'Vizianagaram',
                'West Godavari'
            ],
            'Arunachal Pradesh' => [
                'Tawang',
                'West Kameng',
                'East Kameng',
                'Papum Pare',
                'Kurung Kumey',
                'Kra Daadi',
                'Lower Subansiri',
                'Upper Subansiri',
                'West Siang',
                'East Siang',
                'Upper Siang',
                'Lower Siang',
                'Siang',
                'Lower Dibang Valley',
                'Dibang Valley',
                'Anjaw',
                'Lohit',
                'Changlang',
                'Tirap',
                'Longding'
            ],
            'Assam' => [
                'Baksa',
                'Barpeta',
                'Biswanath',
                'Bongaigaon',
                'Cachar',
                'Charaideo',
                'Chirang',
                'Darrang',
                'Dhemaji',
                'Dhubri',
                'Dibrugarh',
                'Goalpara',
                'Golaghat',
                'Hailakandi',
                'Hojai',
                'Jorhat',
                'Kamrup',
                'Kamrup Metropolitan',
                'Karbi Anglong',
                'Karimganj',
                'Kokrajhar',
                'Lakhimpur',
                'Majuli',
                'Morigaon',
                'Nagaon',
                'Nalbari',
                'Sivasagar',
                'Sonitpur',
                'South Salmara-Mankachar',
                'Tinsukia',
                'Udalguri',
                'West Karbi Anglong'
            ],
            'Bihar' => [
                'Araria',
                'Arwal',
                'Aurangabad',
                'Banka',
                'Begusarai',
                'Bhagalpur',
                'Bhojpur',
                'Buxar',
                'Darbhanga',
                'East Champaran',
                'Gaya',
                'Gopalganj',
                'Jamui',
                'Jehanabad',
                'Kaimur',
                'Katihar',
                'Khagaria',
                'Kishanganj',
                'Lakhisarai',
                'Madhepura',
                'Madhubani',
                'Munger',
                'Muzaffarpur',
                'Nalanda',
                'Nawada',
                'Patna',
                'Purnia',
                'Rohtas',
                'Saharsa',
                'Samastipur',
                'Saran',
                'Sheikhpura',
                'Sheohar',
                'Sitamarhi',
                'Siwan',
                'Supaul',
                'Vaishali',
                'West Champaran'
            ],
            'Chhattisgarh' => [
                'Balod',
                'Baloda Bazar',
                'Balrampur',
                'Bastar',
                'Bemetara',
                'Bijapur',
                'Bilaspur',
                'Dantewada',
                'Dhamtari',
                'Durg',
                'Gariaband',
                'Gaurela-Pendra-Marwahi',
                'Janjgir-Champa',
                'Jashpur',
                'Kabirdham',
                'Kanker',
                'Kondagaon',
                'Korba',
                'Korea',
                'Mahasamund',
                'Mungeli',
                'Narayanpur',
                'Raigarh',
                'Raipur',
                'Rajnandgaon',
                'Sukma',
                'Surajpur',
                'Surguja'
            ],
            'Goa' => [
                'North Goa',
                'South Goa'
            ],
            'Gujarat' => [
                'Ahmedabad',
                'Amreli',
                'Anand',
                'Aravalli',
                'Banaskantha',
                'Bharuch',
                'Bhavnagar',
                'Botad',
                'Chhota Udaipur',
                'Dahod',
                'Dang',
                'Devbhoomi Dwarka',
                'Gandhinagar',
                'Gir Somnath',
                'Jamnagar',
                'Junagadh',
                'Kheda',
                'Kutch',
                'Mahisagar',
                'Mehsana',
                'Morbi',
                'Narmada',
                'Navsari',
                'Panchmahal',
                'Patan',
                'Porbandar',
                'Rajkot',
                'Sabarkantha',
                'Surat',
                'Surendranagar',
                'Tapi',
                'Vadodara',
                'Valsad'
            ],
            'Haryana' => [
                'Ambala',
                'Bhiwani',
                'Charkhi Dadri',
                'Faridabad',
                'Fatehabad',
                'Gurgaon',
                'Hisar',
                'Jhajjar',
                'Jind',
                'Kaithal',
                'Karnal',
                'Kurukshetra',
                'Mahendragarh',
                'Nuh',
                'Palwal',
                'Panchkula',
                'Panipat',
                'Rewari',
                'Rohtak',
                'Sirsa',
                'Sonipat',
                'Yamunanagar'
            ],
            'Himachal Pradesh' => [
                'Bilaspur',
                'Chamba',
                'Hamirpur',
                'Kangra',
                'Kinnaur',
                'Kullu',
                'Lahaul and Spiti',
                'Mandi',
                'Shimla',
                'Sirmaur',
                'Solan',
                'Una'
            ],
            'Jammu and Kashmir' => [
                'Anantnag',
                'Bandipora',
                'Baramulla',
                'Budgam',
                'Doda',
                'Ganderbal',
                'Jammu',
                'Kathua',
                'Kishtwar',
                'Kulgam',
                'Kupwara',
                'Poonch',
                'Pulwama',
                'Rajouri',
                'Ramban',
                'Reasi',
                'Samba',
                'Shopian',
                'Srinagar',
                'Udhampur'
            ],
            'Delhi' => [
                'Central Delhi',
                'East Delhi',
                'New Delhi',
                'North Delhi',
                'North East Delhi',
                'North West Delhi',
                'Shahdara',
                'South Delhi',
                'South East Delhi',
                'South West Delhi',
                'West Delhi'
            ],
            'Kerala' => [
                'Alappuzha',
                'Ernakulam',
                'Idukki',
                'Kannur',
                'Kasaragod',
                'Kollam',
                'Kottayam',
                'Kozhikode',
                'Malappuram',
                'Palakkad',
                'Pathanamthitta',
                'Thiruvananthapuram',
                'Thrissur',
                'Wayanad'
            ],
            'Madhya Pradesh' => [
                'Agar Malwa',
                'Alirajpur',
                'Anuppur',
                'Ashoknagar',
                'Balaghat',
                'Barwani',
                'Betul',
                'Bhind',
                'Bhopal',
                'Burhanpur',
                'Chhatarpur',
                'Chhindwara',
                'Damoh',
                'Datia',
                'Dewas',
                'Dhar',
                'Dindori',
                'Guna',
                'Gwalior',
                'Harda',
                'Hoshangabad',
                'Indore',
                'Jabalpur',
                'Jhabua',
                'Katni',
                'Khandwa',
                'Khargone',
                'Mandla',
                'Mandsaur',
                'Morena',
                'Narsinghpur',
                'Neemuch',
                'Panna',
                'Raisen',
                'Rajgarh',
                'Ratlam',
                'Rewa',
                'Sagar',
                'Satna',
                'Sehore',
                'Seoni',
                'Shahdol',
                'Shajapur',
                'Sheopur',
                'Shivpuri',
                'Sidhi',
                'Singrauli',
                'Tikamgarh',
                'Ujjain',
                'Umaria',
                'Vidisha'
            ],

            'Jharkhand' => [
                'Bokaro',
                'Chatra',
                'Deoghar',
                'Dhanbad',
                'Dumka',
                'East Singhbhum',
                'Garhwa',
                'Giridih',
                'Godda',
                'Gumla',
                'Hazaribagh',
                'Jamtara',
                'Khunti',
                'Koderma',
                'Latehar',
                'Lohardaga',
                'Pakur',
                'Palamu',
                'Ramgarh',
                'Ranchi',
                'Sahebganj',
                'Seraikela Kharsawan',
                'Simdega',
                'West Singhbhum'
            ],
            'Karnataka' => [
                'Bagalkot',
                'Ballari',
                'Belagavi',
                'Bengaluru Rural',
                'Bengaluru Urban',
                'Bidar',
                'Chamarajanagar',
                'Chikkaballapur',
                'Chikkamagaluru',
                'Chitradurga',
                'Dakshina Kannada',
                'Davanagere',
                'Dharwad',
                'Gadag',
                'Hassan',
                'Haveri',
                'Kalaburagi',
                'Kodagu',
                'Kolar',
                'Koppal',
                'Mandya',
                'Mysuru',
                'Raichur',
                'Ramanagara',
                'Shivamogga',
                'Tumakuru',
                'Udupi',
                'Uttara Kannada',
                'Vijayapura',
                'Yadgir'
            ],
            'Maharashtra' => [
                'Mumbai City',
                'Mumbai Suburban',
                'Ahmednagar',
                'Akola',
                'Amravati',
                'Aurangabad',
                'Beed',
                'Bhandara',
                'Bhayandar',
                'Buldhana',
                'Chandrapur',
                'Dhule',
                'Gadchiroli',
                'Gondia',
                'Hingoli',
                'Jalgaon',
                'Jalna',
                'Kolhapur',
                'Latur',
                'Mumbai City',
                'Nagpur',
                'Nanded',
                'Nandurbar',
                'Nashik',
                'Osmanabad',
                'Palghar',
                'Parbhani',
                'Pune',
                'Raigad',
                'Ratnagiri',
                'Sangli',
                'Satara',
                'Sindhudurg',
                'Solapur',
                'Thane',
                'Wardha',
                'Washim',
                'Yavatmal'
            ],
            'Manipur' => [
                'Bishnupur',
                'Chandel',
                'Churachandpur',
                'Imphal East',
                'Imphal West',
                'Jiribam',
                'Kangpokpi',
                'Noney',
                'Senapati',
                'Tamenglong',
                'Tengnoupal',
                'Thoubal',
                'Ukhrul'
            ],
            'Meghalaya' => [
                'East Garo Hills',
                'East Khasi Hills',
                'Jaintia Hills',
                'Ri Bhoi',
                'South Garo Hills',
                'South Khasi Hills',
                'West Garo Hills',
                'West Khasi Hills'
            ],
            'Mizoram' => [
                'Aizawl',
                'Champhai',
                'Kolasib',
                'Lawngtlai',
                'Lunglei',
                'Mamit',
                'Serchhip',
                'Siaha',
                'Thenzawl'
            ],
            'Nagaland' => [
                'Dimapur',
                'Kohima',
                'Mokokchung',
                'Mon',
                'Peren',
                'Phek',
                'Tuensang',
                'Wokha',
                'Zunheboto'
            ],
            'Odisha' => ['Bhubaneswar', 'Cuttack', 'Puri', 'Rourkela', 'Berhampur'],
            'Punjab' => ['Amritsar', 'Ludhiana', 'Jalandhar', 'Patiala', 'Bathinda'],
            'Rajasthan' => ['Jaipur', 'Jodhpur', 'Udaipur', 'Ajmer', 'Bikaner'],
            'Sikkim' => ['Gangtok', 'Namchi', 'Mangan', 'Gyalshing', 'Ravangla'],
            'Tamil Nadu' => ['Chennai', 'Coimbatore', 'Madurai', 'Salem', 'Tiruchirappalli'],
            'Telangana' => ['Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Khammam'],
            'Tripura' => ['Agartala', 'Udaipur', 'Dharmanagar', 'Kailashahar', 'Belonia'],
            'Uttar Pradesh' => ['Lucknow', 'Kanpur', 'Varanasi', 'Agra', 'Meerut'],
            'Uttarakhand' => ['Dehradun', 'Haridwar', 'Nainital', 'Almora', 'Pithoragarh'],
            'West Bengal' => [
                'Alipurduar',
                'Bankura',
                'Birbhum',
                'Cooch Behar',
                'Dakshin Dinajpur',
                'Darjeeling',
                'Hooghly',
                'Howrah',
                'Jalpaiguri',
                'Jhargram',
                'Kalimpong',
                'Kolkata',
                'Malda',
                'Murshidabad',
                'Nadia',
                'North 24 Parganas',
                'Paschim Bardhaman',
                'Paschim Medinipur',
                'Purba Bardhaman',
                'Purba Medinipur',
                'Purulia',
                'South 24 Parganas',
                'Uttar Dinajpur'
            ],
            'Andaman and Nicobar Islands' => ['Port Blair', 'Havelock Island', 'Car Nicobar', 'Neil Island'],
            'Chandigarh' => ['Chandigarh'],
            'Dadra and Nagar Haveli and Daman and Diu' => ['Silvassa', 'Daman', 'Diu'],
            'Ladakh' => ['Leh', 'Kargil'],
            'Lakshadweep' => ['Kavaratti', 'Agatti', 'Amini', 'Andrott'],
            'Puducherry' => ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
        ];

        foreach ($districts as $state => $district) {
            $state_id = State::where('state_name', $state)->first();
            if ($state_id) {
                foreach ($district as $district_name) {
                    District::create([
                        'state_id' => $state_id->id,
                        'district_name' => $district_name,
                        'district_slug' => \Illuminate\Support\Str::slug($district_name),
                    ]);
                }
            }
        }
    }
}
